### ISSUE TITLE
function3 and function4 are in root of repository

### ISSUE THREAD

**Issue by stefanv** [machine-shop/evenflow#22]
Either remove or move to appropriate place

**Comment by arkwave** [comment]
yeah these functions need to be removed. how does one do that with a pull request?

**Comment by stefanv** [comment]
git checkout -b remove_leftovers
git rm filename
git commit -m "Remove files"
git push myremote remove_leftovers

**Comment by arkwave** [comment]
Done!

**Comment by stefanv** [comment]
Closed by https://github.com/machine-shop/evenflow/pull/23
