### ISSUE TITLE
Travis-ci Python does not have access to system packages

### ISSUE THREAD

**Issue by stefanv** [machine-shop/evenflow#31]
Needs:

```
virtualenv:
  system_site_packages: true
```

See http://danielnouri.org/notes/2012/11/23/use-apt-get-to-install-python-dependencies-for-travis-ci/

**Comment by arkwave** [comment]
Just made the pull request! Thanks for catching that.

**Comment by stefanv** [comment]
Meh, it looks like it may be a bit trickier than that.  @jerryz123 Can you make a PR against this project's travis.yml so that they get numpy & scipy installed correctly?  I guess no matplotlib needed for now.
